# docker-compose.yml
version: '3.3'

services:
  gemini-validator:
    build: .
    env_file: .env
    environment:
      - http_proxy=http://wwwproxy.osakac.ac.jp:8080
      - https_proxy=http://wwwproxy.osakac.ac.jp:8080
    volumes:
      - .:/app
    tty: true
    stdin_open: true
