# docker-compose.yml
version: '3.8'

services:
  gemini-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=appuser
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - http_proxy=http://wwwproxy.osakac.ac.jp:8080
      - https_proxy=http://wwwproxy.osakac.ac.jp:8080
      - HTTP_PROXY=http://wwwproxy.osakac.ac.jp:8080
      - HTTPS_PROXY=http://wwwproxy.osakac.ac.jp:8080
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    entrypoint: ["/app/docker/entrypoint.sh"]
    tty: true
    stdin_open: true